# Golang CircleCI 2.0 configuration file
# vim:set ts=2 sts=2 sw=2:
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/masahide/inet-ip.info
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: cp ga_id.go.example ga_id.go
      - run: git tag -l 
      - run: mkdir -p $TEST_RESULTS
      - run: go get -v -t -d ./... | tee ${TEST_RESULTS}/go-test.out
      - run: go test -v ./... | tee -a ${TEST_RESULTS}/go-test.out
      - run: test -z "$(gofmt -s -l main.go | tee -a ${TEST_RESULTS}/go-test.out)"
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
  release:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/masahide/inet-ip.info
    environment:
      TEST_RESULTS: /tmp/release-results
    steps:
      - checkout
      - run: go get -v -t -d ./... | tee ${TEST_RESULTS}/go-test.out
      - run: go test -v ./... | tee -a ${TEST_RESULTS}/go-test.out
      - run: go get -v -t -d ./... | tee ${TEST_RESULTS}/go-test.out
      - run: go test -v ./... | tee -a ${TEST_RESULTS}/go-test.out
      - run: test -z "$(gofmt -s -l main.go | tee -a ${TEST_RESULTS}/go-test.out)"
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: gox --osarch "linux/386 linux/amd64 darwin/386 darwin/amd64" -ldflags "-X main.Version=$(git describe --always --dirty) -X main.Date=${BUILD_DATE}" -output "dist/{{.OS}}_{{.Arch}}/${CIRCLE_PROJECT_REPONAME}"
      - run: cd dist;for i in $(ls);do tar -cvzf "${CIRCLE_PROJECT_REPONAME}_${i}.tar.gz" "${i}";rm -rf "${i}";done
      - run: ghr -t "${GITHUB_TOKEN}" -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" --replace `git describe --tags` dist/ 
      - store_artifacts:
          path: dist
          destination: build_tar_gz
      - store_test_results:
          path: dist

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
      - release:
          filters:
            branches:
              only: /v.*/
